- src/slots/Sidebar/index.tsx
- src/store/selectors.ts
- src/store/useSiteStore.ts
> :bug: fix: 修正首页白屏的问题

- src/components/GithubButton/index.tsx
> :bug: fix: 修正 GithubButton 无法正常渲染的问题

- src/pages/Docs/styles.ts
- src/slots/LangSwitch/index.tsx
- src/styles/customToken.ts
- tsconfig-check.json
> :bug: fix: 修正 contentMaxWidth 不支持字符串的问题

- src/slots/SearchBar/index.tsx
> :bug: fix: 修正任意编辑框内输入斜杠时搜索框抢夺焦点的问题

- src/slots/Sidebar/style.ts
> Incomplete display of menus

- example/.dumirc.ts
- src/components/Hero/index.tsx
- src/types/hero.ts
> :bug: fix: 修正 link 无法跳转新页面的问题

- example/docs/changelog.md
- example/docs/config/index.zh-CN.md
- example/docs/config/markdown.zh-CN.md
- example/docs/demos/Antd.tsx
- example/docs/guide/theme.zh-CN.md
- src/components/Toc/index.tsx
- src/components/Toc/style.ts
- src/layouts/DocLayout/index.tsx
- src/pages/Docs/index.tsx
- src/pages/Docs/styles.ts
- src/store/index.ts
- src/store/selectors/index.ts
- src/store/selectors/token.ts
- src/styles/customStylish.ts
> ✨ feat: 支持文档级别的 token 配置

- src/layouts/DocLayout/index.tsx
> :bug: fix: 移除 StrictMode

- package.json
- src/builtins/Previewer/index.tsx
- src/slots/Content/index.tsx
close  [ant-design/pro-components@#6996](https://github.com/ant-design/pro-components/issues/6996)
> feat: support lazy load demo

- example/docs/config/index.zh-CN.md
- src/slots/Footer/index.tsx
- src/types/config.ts
> ✨ feat: 给footerConfig添加一个参数leftBottom，用以控制’版本信息‘模块

- src/slots/Navbar/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
navbar支持外链
> feat: navbar支持外链

- example/docs/config/index.en-US.md
- example/docs/config/index.zh-CN.md
- src/store/selectors/apiHeader.test.ts
- src/store/selectors/apiHeader.ts
Closes #74
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> :sparkles: feat: Feature atomId插值变量风格转换

- package.json
- src/layouts/DocLayout/index.tsx
- src/store/useSiteStore.ts
- src/store/useThemeStore.ts
- src/styles/theme/dark.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
refactor with zustand v4.4, refs: https://github.com/pmndrs/zustand/issues/1982
> :bug: fix: fix zustand v4.4 Breaking Change

- package.json
- tests/selectors.test.ts
- tsconfig.json
refs: https://github.com/vitest-dev/vitest/issues/4043
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
refs: https://github.com/vitest-dev/vitest/issues/4043#issuecomment-1713026327
> :white_check_mark: test: fix test due to vitest upgrade

- src/slots/Footer/index.tsx
- \[ ] ✨ feat
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
``` ts
const columns =
footer?.columns === false
? undefined
: getColumns({ github: githubUrl || (pkg as any).homepage });
```
to 
``` ts
const columns = footer?.columns
? footer?.columns
: getColumns({ github: githubUrl || (pkg as any).homepage });
````
测试结果显示：
> :bug: fix(slots-foolter-index): 修复Footer中支持自定义 columns 数据问题

- src/components/StoreUpdater/index.tsx
- src/slots/ContentFooter/Linker.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
修复首页 tab、上一篇、下一篇国际化问题
fix https://github.com/arvinxx/dumi-theme-antd-style/issues/90
> :bug: fix: 修复顶部首页、上下篇多语言问题

- src/slots/ContentTabs/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
修复页面 tab 默认按钮国际化未生效错误
ref: https://github.com/umijs/dumi/blob/1928eb9e5ea3b63f3e49554a8d2f693271d1073c/src/client/theme-default/locales/zh-CN.json#L34
> :bug: fix: page-tab internationalization error

- src/components/Toc/style.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
https://github.com/arvinxx/dumi-theme-antd-style/issues/97
> 🐛 fix:  remove border-radius of Toc

- tsconfig.json
- vitest.config.ts
fix test,refs  #105 
@FriedRiceNoodles
> :green_heart: ci: fix test

- src/slots/Header/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
close https://github.com/arvinxx/dumi-theme-antd-style/issues/109
> 🐛 fix: 修复themeConfig.prefersColor.switch配置不生效的问题

- src/components/NativeSelect/SelectItem/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
使用`forwardRef`本身的泛型代替`React.FC`进行类型声明。
fixed [114.](https://github.com/arvinxx/dumi-theme-antd-style/issues/114).
> 🐛 fix: 修复类型错误,使CI流程恢复正常

- src/types/config.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[x] 📝 docs
> :bookmark: chore: 修正一处错误的注释

- example/docs/config/index.zh-CN.md
- src/slots/Logo/index.tsx
- src/slots/Logo/style.ts
- src/types/config.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
相关issue：https://github.com/arvinxx/dumi-theme-antd-style/issues/116
> ✨ feat: 支持通过配置隐藏header的name部分

- package.json
- src/components/StoreUpdater/index.tsx
- src/components/StoreUpdater/useRouteMeta.ts
- src/store/useSiteStore.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
dumi 上游: https://github.com/umijs/dumi/issues/2124
下游使用: https://github.com/ant-design/pro-components/issues/8426
> 🐛 fix: 修复页面白屏错误
